### ISSUE TITLE
Separate Bitwise Operations from Bytewise

### ISSUE THREAD

**Issue by boomshroom** [Coder-256/num-traits-flexible#4]
Essentially put functions to swap or rotate bytes along with those that change endianness in a separate trait from the functions for bitwise logic and shifting. I would like this to be usable with the uX library which provides integers with non-byte multiple bit-widths. It doesn't really make sense to swap the bytes of an integer with 43 bits. (That's prime by the way.)

Since here we're building a new set of traits for num-traits, it would be nice to implement this for libraries such as uX before things have stabilized again.

**Comment by jacob-greenfield** [comment]
That's a great idea! I'm actually planning on creating an entirely different project, [magic-numbers](https://github.com/Coder-256/magic-numbers) (it looks pretty empty now mostly because I'm still figuring out how to classify complex numbers). I'll implement this there when I am reorganizing. I'm happy to see that there's interest in this project.

**Comment by jacob-greenfield** [comment]
Coder-256/magic-numbers@a8960699eb95263a0f0f6b1caa6596b6789fd201

Let me know if I missed anything

**Comment by boomshroom** [comment]
Looks like you got everything! Often it can be good to start fresh because then you have the freedom to change things.
